import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout(
	{ children }: Readonly<{ children: React.ReactNode;}>
) {
	return (
		<div className="flex flex-col min-h-screen">
		<header className="border-b bg-gray-800 text-white">
			<div className="container mx-auto px-4 py-2 flex items-center justify-between">
				<div className=" flex items-center gap-4">
					<Button className="bg-gray-800 text-white hover:bg-gray-700" asChild>
						<Link href="/" className="font-bold text-xl">Top</Link>
					</Button>
				</div>
				<div className=" flex items-center gap-3">
					<Button className="bg-gray-800 text-white hover:bg-gray-700" asChild>
						<Link href="/login">ログイン</Link>
					</Button>
					<Button className="bg-gray-800 text-white hover:bg-gray-700" asChild>
						<Link href="/register">登録</Link>
					</Button>
				</div>
			</div>
		</header>

		<main className="flex-1">
			{children}
		</main>
		
		<hr />
		<footer className="px-4 py-1 text-center">
				{/* 両サイドにロゴ画像を表示 */}
				<div className="flex justify-between items-center mb-8">
					<Image
						src="/logo/Logo1.png"
						alt="Logo1"
						width={200}
						height={80}
						priority
					/>
					<Image
						src="/logo/Logo2.png"
						alt="Logo2"
						width={250}
						height={80}
						priority
					/>
				</div>
		</footer>
		</div>
	);
}
