-- CreateTable
CREATE TABLE `IMroll` (
    `id` VARCHAR(191) NOT NULL,
    `taper_code` VARCHAR(191) NOT NULL,
    `imr_set_code` VARCHAR(191) NOT NULL,
    `imr_id` VARCHAR(191) NOT NULL,
    `cylindricity1` DOUBLE NOT NULL,
    `cylindricity2` DOUBLE NOT NULL,
    `cylindricity3` DOUBLE NOT NULL,
    `cylindricity4` DOUBLE NOT NULL,
    `cylindricity5` DOUBLE NOT NULL,
    `pair_diff` DOUBLE NOT NULL,
    `imr_diameter_before` DOUBLE NOT NULL,
    `imr_diameter_after` DOUBLE NOT NULL,
    `grinding_amount` DOUBLE NOT NULL,
    `grinding_type` VARCHAR(191) NULL,
    `imr_ra` DOUBLE NULL,
    `judgement` VARCHAR(191) NOT NULL,
    `comment` VARCHAR(191) NULL,
    `operation_date` VARCHAR(191) NOT NULL,
    `processing_time` DOUBLE NULL,
    `non_processing_code1` VARCHAR(191) NULL,
    `non_processing_time1` DOUBLE NULL,
    `non_processing_code2` VARCHAR(191) NULL,
    `non_processing_time2` DOUBLE NULL,
    `non_processing_code3` VARCHAR(191) NULL,
    `non_processing_time3` DOUBLE NULL,
    `non_processing_code4` VARCHAR(191) NULL,
    `non_processing_time4` DOUBLE NULL,
    `non_processing_code5` VARCHAR(191) NULL,
    `non_processing_time5` DOUBLE NULL,
    `operator` VARCHAR(191) NOT NULL,
    `operation_group` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
