import type { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { CurrentTime } from "@/components/CurrentTime";


export const metadata: Metadata = {
  title: "中間ロール",
  description: "Generated by create next app",
};

export default function PublicLayout(
	{ children }: Readonly<{ children: React.ReactNode;}>
) {
	return (
		<div className="flex flex-col min-h-screen">
			<header className="border-b bg-gray-800 fixed top-0 left-0 w-full z-50">
				<div className="container mx-auto px-2 py-2 flex items-center justify-between">

					<div className=" flex items-center gap-4">
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/" className="font-bold text-xl">Top</Link>
						</Button>
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/imroll" className="font-bold text-xl">IMR一覧</Link>
						</Button>
					</div>

					{/* 時刻表示 */}
					<div className="font-bold text-xl text-gray-300"><CurrentTime /></div>
					
					<div>
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/imroll/create" className="font-bold text-xl">研削実績登録</Link>
						</Button>
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/imroll/list" className="font-bold text-xl">編集</Link>
						</Button>
					</div>
				</div>
			</header>

			<main className="flex-1 pt-16">
				{children}
			</main>
		</div>
	);
}
