import type { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";


export const metadata: Metadata = {
  title: "3D-CG",
  description: "Generated by create next app",
};

export default function PublicLayout(
	{ children }: Readonly<{ children: React.ReactNode;}>
) {
	return (
		<div className="flex flex-col min-h-screen">
			<header className="border-b bg-gray-800">
				<div className="container mx-auto px-2 py-2 flex items-center justify-between">

					<div className=" flex items-center gap-4">
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/" className="font-bold text-xl">Top</Link>
						</Button>
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/r3f" className="font-bold text-xl">3D</Link>
						</Button>
					</div>
				</div>
			</header>

			<main className="flex-1">
				{children}
			</main>
		</div>
	);
}
