import type { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { CurrentTime } from "@/components/workroll/CurrentTime";


export const metadata: Metadata = {
  title: "ワークロール",
  description: "Generated by create next app",
};

export default function PublicLayout(
	{ children }: Readonly<{ children: React.ReactNode;}>
) {
	return (
		<div className="flex flex-col min-h-screen">
			<header className="border-b bg-gray-800">
				<div className="container mx-auto px-2 py-2 flex items-center justify-between">

					<div className=" flex items-center gap-4">
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/" className="font-bold text-xl">Top</Link>
						</Button>
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/workroll" className="font-bold text-xl">Board</Link>
						</Button>
					</div>

					{/* 時刻表示 */}
					<div className="font-bold text-xl text-gray-300"><CurrentTime /></div>
					
					<div>
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/workroll/create" className="font-bold text-lg">登録</Link>
						</Button>
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/workroll/list" className="font-bold text-lg">編集</Link>
						</Button>
						<Button className="bg-gray-800 text-gray-300 hover:bg-gray-700" asChild>
							<Link href="/workroll/count" className="font-bold text-lg">集計</Link>
						</Button>
					</div>
				</div>
			</header>

			<main className="flex-1">
				{children}
			</main>
		</div>
	);
}
